# Generated by Django 3.2.5 on 2021-07-24 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('client_updated', models.DateTimeField(auto_now=True)),
                ('client_created', models.DateTimeField(auto_now_add=True)),
                ('client_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_updated', models.DateTimeField(auto_now=True)),
                ('project_created', models.DateTimeField(auto_now_add=True)),
                ('project_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_client', to='ClientProject.client')),
                ('project_created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_users', models.ManyToManyField(blank=True, related_name='project_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
